CREATE DATABASE DB_KENMORE_AIR ON PRIMARY
(	NAME = N'DB_KENMORE_AIR',
FILENAME = N'C:\Projetos_Ti\Kenmore Airline\KENMORE_AIRLINE_DB.MDF', SIZE = 3072KB,
MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB)
LOG ON
(	NAME = N'DB_KENMORE_AIR_LOG',
FILENAME = N'C:\Projetos_Ti\Kenmore Airline\KENMORE_AIRLINE_DB.LDF', SIZE = 1024KB,
MAXSIZE = 2048KB, FILEGROWTH = 10%)
COLLATE LATIN1_GENERAL_CI_AS